// Ticket 05's tables.  THROWAWAY - startup-remediation effort only.
//
//   node perf-harness/t05-tables.js <sweep.json>
//
// Reads only; re-measures nothing.  Every figure is computed per run and only
// then reduced to a median, so it carries a spread; every cross-arm figure is
// paired by run index against the same session's `none` arm.
const fs = require('fs');

const [SWEEP] = process.argv.slice(2);
if (!SWEEP) {
    console.error('usage: t05-tables.js <sweep.json>');
    process.exit(1);
}
const j = JSON.parse(fs.readFileSync(SWEEP));

const median = (xs) => {
    const s = [...xs].sort((a, b) => a - b);
    const m = s.length >> 1;
    return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2;
};
const spread = (xs) => (xs.length < 2 ? 0 : (Math.max(...xs) - Math.min(...xs)) / 2);
const f1 = (x) => (Math.round(x * 10) / 10).toLocaleString('en-US');

const ARMS = ['pollnow', 'pollfast', 'loadevent'];
/* The map's floor: below this a change cannot be told from session drift. */
const FLOOR = 50;

/* The only interval an arm here can move.  iframePoll.start is where the
 * baseline arms its interval, so everything before it - setProgress's double rAF
 * included - belongs to another ticket. */
const pollWait = (r) => r.marks?.['phase.loading.end'] - r.marks?.['iframePoll.start'];
const loading = (r) => r.marks?.['phase.loading.end'] - r.marks?.['phase.loading.start'];
const loaderRemoved = (r) => r.external?.loaderRemoved;
const drained = (r) => r.windows?.toDrained;
/* Within-run, so it carries none of the whole load's variance.  A change that
 * moves when work runs relative to the rendering steps is judged on this too. */
const frameLag = (r) => r.windows?.toLoaderRemovedFrame - r.windows?.toLoaderRemoved;
const ticks = (r) => r.counts?.['iframePoll.ticks'] ?? 0;
const resolvedBy = (r) => ['immediate', 'event', 'poll']
    .find(h => r.counts?.[`iframeReady.${h}`] > 0) ?? '?';

const groups = {};
for (const a of j.results) {
    (groups[`${a.slug}|${a.tier}`] ??= {})[a.ablate] = a.runs.filter(r => !r.error);
}
const slugs = [...new Set(j.results.map(r => r.slug))].sort();
const tiers = [...new Set(j.results.map(r => r.tier))].sort((a, b) => a - b);

/* Paired: the delta is computed per run index and only then reduced, so it has a
 * spread of its own.  Differencing two medians would throw that away, and the
 * evidence bar is "a delta larger than the measured spread". */
function paired(arms, arm, f) {
    const d = arms[arm].map((r, i) => f(r) - f(arms.none[i])).filter(Number.isFinite);
    if (!d.length) {
        return null;
    }
    const m = median(d), s = spread(d);
    return { m, s, resolved: Math.abs(m) > s };
}
const cell = (p) => (p === null ? '-'
    : `${p.m > 0 ? '+' : ''}${f1(p.m)}±${f1(p.s)}${p.resolved ? '' : ' *ns*'}`);

function payoff(tier, f, label) {
    console.log(`\n### ${label}, ${tier}x — paired against each fixture's own \`none\` arm\n`);
    console.log('| slug | `none` | ' + ARMS.map(a => `\`${a}\` Δ`).join(' | ') + ' |');
    console.log('|---|---|' + ARMS.map(() => '---').join('|') + '|');
    for (const slug of slugs) {
        const arms = groups[`${slug}|${tier}`];
        if (!arms?.none) {
            continue;
        }
        const b = arms.none.map(f).filter(Number.isFinite);
        console.log(`| \`${slug}\` | ${f1(median(b))}±${f1(spread(b))} | `
            + ARMS.map(a => cell(paired(arms, a, f))).join(' | ') + ' |');
    }
}

/* Worst-filing milliseconds removed at 1x is the map's ranking key; breadth is
 * how many fixtures clear the floor with a delta larger than its own spread. */
function ranking(tier, f, label) {
    console.log(`\n### Ranking key — ${label}, ${tier}x\n`);
    console.log('| arm | worst-filing Δ | on | breadth (resolved and ≥ 50 ms) |');
    console.log('|---|---|---|---|');
    for (const arm of ARMS) {
        let best = null, bestSlug = '', breadth = [];
        for (const slug of slugs) {
            const arms = groups[`${slug}|${tier}`];
            const p = arms?.none && paired(arms, arm, f);
            if (!p) {
                continue;
            }
            if (best === null || p.m < best) {
                best = p.m;
                bestSlug = slug;
            }
            if (p.resolved && -p.m >= FLOOR) {
                breadth.push(slug);
            }
        }
        console.log(`| \`${arm}\` | ${f1(best)} | \`${bestSlug}\` | ${breadth.length}/${slugs.length}`
            + (breadth.length ? ` — ${breadth.map(s => `\`${s}\``).join(', ')}` : '') + ' |');
    }
}

console.log(`# Ticket 05 tables — event-driven source-document load

Generated by \`perf-harness/t05-tables.js\` from \`${SWEEP.split('/').pop()}\`.
Session \`${j.stamp}\`, ${j.chrome}, ${j.machine?.model} (${j.machine?.cpus} cpu),
runs=${j.runs} per (fixture, tier, arm), level=${j.level}.
Build \`${j.arms?.[0]?.branch}\` @ \`${(j.arms?.[0]?.sha ?? '').slice(0, 8)}\`\
${j.arms?.[0]?.dirty ? ' + the ticket-05 arms, uncommitted at sweep time and committed unchanged as `757f077a`' : ''}.
All ${j.arms?.length} arms are the same bundle on the same server, alternating run
by run, so a delta cannot be a build or a server difference.

\`±\` is half the min→max range, the convention \`t04-tables.js\` used. \`*ns*\`
marks a delta no larger than that — it does not clear the evidence bar, whatever
its sign. \`report-ablation.js\` prints the *full* range under the same \`±\`, so
its \`*unresolved*\` markers are twice as strict; the one row where the two
conventions disagree is called out in the ticket answer.`);

for (const tier of tiers) {
    payoff(tier, pollWait, 'The readiness wait (`iframePoll.start` → `phase.loading.end`)');
}
for (const tier of tiers) {
    payoff(tier, loaderRemoved, 'Window 1: nav start → loader removed (externally observed)');
}
for (const tier of tiers) {
    payoff(tier, drained, 'Window 2: nav start → fully drained');
}
for (const tier of tiers) {
    ranking(tier, pollWait, 'the readiness wait');
}

console.log('\n### Mechanism — what ended the wait, and what the interval actually delivered\n');
console.log('| slug | tier | arm | resolved by | ticks | wait ms | ms per tick |');
console.log('|---|---|---|---|---|---|---|');
for (const slug of slugs) {
    for (const tier of tiers) {
        const arms = groups[`${slug}|${tier}`];
        if (!arms) {
            continue;
        }
        for (const arm of ['none', ...ARMS]) {
            const runs = arms[arm] ?? [];
            const how = runs.map(resolvedBy).reduce((a, h) => (a[h] = (a[h] ?? 0) + 1, a), {});
            const t = median(runs.map(ticks));
            const w = median(runs.map(pollWait).filter(Number.isFinite));
            console.log(`| \`${slug}\` | ${tier}x | \`${arm}\` | `
                + Object.entries(how).map(([h, n]) => `${h}×${n}`).join(' ')
                + ` | ${f1(t)} | ${f1(w)} | ${t > 0 ? f1(w / t) : '—'} |`);
        }
    }
}

console.log('\n### Frame lag — loader removal to the second rAF after it, within-run\n');
console.log('| slug | tier | `none` | ' + ARMS.map(a => `\`${a}\` Δ`).join(' | ') + ' |');
console.log('|---|---|---|' + ARMS.map(() => '---').join('|') + '|');
for (const slug of slugs) {
    for (const tier of tiers) {
        const arms = groups[`${slug}|${tier}`];
        if (!arms?.none) {
            continue;
        }
        const b = arms.none.map(frameLag).filter(Number.isFinite);
        console.log(`| \`${slug}\` | ${tier}x | ${f1(median(b))}±${f1(spread(b))} | `
            + ARMS.map(a => cell(paired(arms, a, frameLag))).join(' | ') + ' |');
    }
}

console.log('\n### Phase check — `phase.loading` moves with the wait\n');
for (const tier of tiers) {
    payoff(tier, loading, 'Whole `phase.loading`');
}
