#!/usr/bin/env node

/*
 * Rewrites a generated viewer into the metadata shape viewers carried before
 * text block values moved into a second script tag: every value inline on its
 * fact, no sidecar, no `textBlockValues` key.  Viewers in that shape have to
 * keep working, so the puppeteer suite renders one alongside the shape the
 * generator emits today and asserts they agree.
 *
 * Failing when there is no sidecar is the point as much as the rewrite is: it
 * is the cheapest proof that the viewer under test was generated by the working
 * tree's plugin rather than by an older copy that happened to be installed.
 *
 * Usage: node inline_text_block_values.mjs <viewer.htm> <output.htm>
 */

import fs from 'fs';

const VIEWER_DATA_SCRIPT_TYPE = 'application/x.ixbrl-viewer+json';
const TEXT_BLOCK_VALUES_SCRIPT_TYPE = 'application/x.ixbrl-viewer-textblocks+json';

/* The generator JSON-escapes <, > and & in both payloads, so neither can
 * contain a tag and matching the script elements with a pattern is safe. */
function scriptPattern(type) {
    const literalType = type.replace(/[.+*?^$()[\]{}|\\]/g, '\\$&');
    return new RegExp(`<script type="${literalType}">(.*?)</script>`, 's');
}

function escapeJSONForScriptTag(json) {
    return json
        .replace(/</g, '\\u003C')
        .replace(/>/g, '\\u003E')
        .replace(/&/g, '\\u0026')
        /* The generator writes JSON with Python's default ASCII escaping.  A
         * viewer that kept its non-ASCII characters raw would be decoded by the
         * charset the server happens to send rather than by the document, which
         * would make the two shapes differ for a reason that has nothing to do
         * with where the values are held. */
        .replace(/[\u0080-\uffff]/g, c =>
            '\\u' + c.charCodeAt(0).toString(16).padStart(4, '0'));
}

function fail(message) {
    console.error(`inline_text_block_values: ${message}`);
    process.exit(1);
}

const [inputPath, outputPath] = process.argv.slice(2);
if (inputPath === undefined || outputPath === undefined) {
    fail('usage: inline_text_block_values.mjs <viewer.htm> <output.htm>');
}

const viewer = fs.readFileSync(inputPath, 'utf-8');

const sidecarMatch = viewer.match(scriptPattern(TEXT_BLOCK_VALUES_SCRIPT_TYPE));
if (sidecarMatch === null) {
    fail(`${inputPath} has no ${TEXT_BLOCK_VALUES_SCRIPT_TYPE} script tag, so it `
        + 'was not generated by this working tree\'s plugin');
}
const taxonomyDataMatch = viewer.match(scriptPattern(VIEWER_DATA_SCRIPT_TYPE));
if (taxonomyDataMatch === null) {
    fail(`${inputPath} has no ${VIEWER_DATA_SCRIPT_TYPE} script tag`);
}

const deferredValues = JSON.parse(sidecarMatch[1]);
const taxonomyData = JSON.parse(taxonomyDataMatch[1]);

/* Keys are the viewer's own fact identifier - the source report's index, a
 * hyphen, then the fact's ID - and a fact ID can appear in more than one target
 * report of that source report. */
for (const [key, value] of Object.entries(deferredValues)) {
    const [, sourceReportIndex, factId] = key.match(/^(\d+)-(.*)$/);
    const sourceReport = taxonomyData.sourceReports?.[Number(sourceReportIndex)];
    const facts = (sourceReport?.targetReports ?? [])
        .map(targetReport => targetReport.facts?.[factId])
        .filter(fact => fact !== undefined);
    if (facts.length === 0) {
        fail(`deferred value ${key} matches no fact in the taxonomy data`);
    }
    facts.forEach(fact => { fact.v = value; });
}
delete taxonomyData.textBlockValues;

const inlined = viewer
    .replace(taxonomyDataMatch[0],
        `<script type="${VIEWER_DATA_SCRIPT_TYPE}">`
        + escapeJSONForScriptTag(JSON.stringify(taxonomyData, null, 1))
        + '</script>')
    .replace(sidecarMatch[0], '');

fs.writeFileSync(outputPath, inlined);
console.log(`Inlined ${Object.keys(deferredValues).length} text block value(s): `
    + `${inputPath} -> ${outputPath}`);
